// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBye_b5HklYDD9shvWranc3p23cgZMrcHU',
    appId: '1:180526083102:web:15b7decbd5b2e31129520f',
    messagingSenderId: '180526083102',
    projectId: 'app-9c7f4',
    authDomain: 'app-9c7f4.firebaseapp.com',
    storageBucket: 'app-9c7f4.appspot.com',
    measurementId: 'G-NJGRZ0KTL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZVivPK8wtZ2zqnbPYcIkwp4xayjgiO7U',
    appId: '1:180526083102:android:70e7fba16d832d7129520f',
    messagingSenderId: '180526083102',
    projectId: 'app-9c7f4',
    storageBucket: 'app-9c7f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0I2-YbsrSw9pLoFEI2diZ_U8P_qSZp7M',
    appId: '1:180526083102:ios:acf70407c716a56929520f',
    messagingSenderId: '180526083102',
    projectId: 'app-9c7f4',
    storageBucket: 'app-9c7f4.appspot.com',
    iosBundleId: 'com.example.amazonapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0I2-YbsrSw9pLoFEI2diZ_U8P_qSZp7M',
    appId: '1:180526083102:ios:acf70407c716a56929520f',
    messagingSenderId: '180526083102',
    projectId: 'app-9c7f4',
    storageBucket: 'app-9c7f4.appspot.com',
    iosBundleId: 'com.example.amazonapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBye_b5HklYDD9shvWranc3p23cgZMrcHU',
    appId: '1:180526083102:web:fb5034d49766728729520f',
    messagingSenderId: '180526083102',
    projectId: 'app-9c7f4',
    authDomain: 'app-9c7f4.firebaseapp.com',
    storageBucket: 'app-9c7f4.appspot.com',
    measurementId: 'G-23H6ZNP4HD',
  );
}
