// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAwPlVTWeO6fXQ6L4EFOIlkXVa33EZozM',
    appId: '1:558662360216:web:058038b982b10752f284ed',
    messagingSenderId: '558662360216',
    projectId: 'fir-ca8d3',
    authDomain: 'fir-ca8d3.firebaseapp.com',
    storageBucket: 'fir-ca8d3.appspot.com',
    measurementId: 'G-X3D8FF5VZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClWApKZAVnkiVZF3ynLq-O4khIalrqAP0',
    appId: '1:558662360216:android:7c24fddb5174f840f284ed',
    messagingSenderId: '558662360216',
    projectId: 'fir-ca8d3',
    storageBucket: 'fir-ca8d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWb7zAhSnNxrUldoYqniCDGKpYVPDlhW8',
    appId: '1:558662360216:ios:dfa9087bc0599a61f284ed',
    messagingSenderId: '558662360216',
    projectId: 'fir-ca8d3',
    storageBucket: 'fir-ca8d3.appspot.com',
    iosBundleId: 'com.example.amazonapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWb7zAhSnNxrUldoYqniCDGKpYVPDlhW8',
    appId: '1:558662360216:ios:dfa9087bc0599a61f284ed',
    messagingSenderId: '558662360216',
    projectId: 'fir-ca8d3',
    storageBucket: 'fir-ca8d3.appspot.com',
    iosBundleId: 'com.example.amazonapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAwPlVTWeO6fXQ6L4EFOIlkXVa33EZozM',
    appId: '1:558662360216:web:b63f96221f448e51f284ed',
    messagingSenderId: '558662360216',
    projectId: 'fir-ca8d3',
    authDomain: 'fir-ca8d3.firebaseapp.com',
    storageBucket: 'fir-ca8d3.appspot.com',
    measurementId: 'G-ZE37VNG6JY',
  );
}
